### PR TITLE
Add "lucky search" to Members search

### PR DESCRIPTION
**Pull request by maxplt**
# Jira Issue: [IP-43](https://hedvig.atlassian.net/jira/software/projects/IP/boards/19?selectedIssue=IP-43)

## What?
Add "lucky search" to Members search

## Why?
For better UX

## Video
https://user-images.githubusercontent.com/89198006/133027785-9f9fa4d4-a88d-4d61-b899-c65df5c26193.mov

## Optional checklist
- [x] Updated `src/changelog.ts`
- [ ] Codescouted
- [ ] Unit tests written
- [x] Tested locally

### CODE REVIEW

**Review by rasmusguterstam — CHANGES_REQUESTED** [review]
This looks great! But, I'm thinking that we're adding an extra step here when we really want to make it more efficient; perhaps we could do lucky search when "control" is pressed? And just hint in a similar way as we do with the shortcut for notes:

https://user-images.githubusercontent.com/51323202/133031638-a24bcae0-cd29-4a76-99ea-616ed4ce298e.mov

I'm also thinking that it would be neat if the lucky search kicked in automatically if the search result is just 1 member - we're probably going to select it anyway, right? 

What do you think? 😄

**Comment by maxplt** [comment]
Yeah, I got it 👌
Agree with everything 🔥
Will add this features!

**Comment by maxplt** [comment]
# Add new features:
https://user-images.githubusercontent.com/89198006/133074234-1f73bf41-a2c6-4e23-a7f9-65ed29b7a80a.mov

**Comment by maxplt** [comment]
### Little style changes
image

**Review by rasmusguterstam — APPROVED** [review]
Yesss this is really clean 🌟

**Pull request merged**
