### PR TITLE
mdx-editor prototype

### PR DESCRIPTION
**Pull request by alebedev**
## What?
Demo of markdown editor in claim notes (based on mdx-editor)

Previous notes displayed in plain text

## Why?
-

## If applicable, rooms for improvement?
- Styling for editor elements and content

## Optional checklist
- [ ] Codescouted
- [ ] Unit tests written
- [x] Tested locally

### CODE REVIEW

**Comment by alebedev** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/HedvigInsurance/hedgehog/1209?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1208** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/hedgehog/1208?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1209** <a href="https://app.graphite.dev/github/pr/HedvigInsurance/hedgehog/1209?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/hedgehog/1209?utm_source=stack-comment).

**Review by guilhermespopolin — APPROVED** [review]
With the risk of having premature changes ,aybe it would be nice to move/abstract `MarkdowEditor` on its own file. That way we could simplify its API for consumers and, if decided to use a different solution for markdown, we could concentrate the changes on that single file (while trying to keep the same API).

**Comment by alebedev** [comment]
@guilhermespopolin you just described my next PR :)

**Comment by alebedev** [comment]
### Merge activity

* **Jan 29, 6:52 AM**: @alebedev started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/HedvigInsurance/hedgehog/1209).

**Review by falklinus — APPROVED** [review]
Looks good, maybe we could even have "RichTextEditor" with these default settings to be able to use it easily for other kinds of input as well, not just claim notes

**Comment by falklinus** [comment]
Oh sorry didn't read the comments...

**Pull request merged**
